#!/bin/bash

# Colors
GREEN="\033[0;32m"
BLUE="\033[0;34m"
YELLOW="\033[1;33m"
CYAN="\033[0;36m"
RESET="\033[0m"

echo ""
echo -e "${CYAN}═══════════════════════════════════════════════════════${RESET}"
echo -e "${GREEN}         SRE Lab Architecture${RESET}"
echo -e "${CYAN}═══════════════════════════════════════════════════════${RESET}"
echo ""

echo -e "${GREEN}sre-lab${RESET} ${CYAN}(AlmaLinux 9 Host - 16GB RAM, 80GB Disk)${RESET}"
echo ""
echo -e "├── ${BLUE}sre-vm1${RESET} ${YELLOW}(192.168.122.152)${RESET}"
echo -e "│   ├── Nginx :80"
echo -e "│   ├── Node.js App :3000"
echo -e "│   ├── Gitea :3001"
echo -e "│   └── Node Exporter :9100"
echo ""
echo -e "├── ${BLUE}sre-db${RESET} ${YELLOW}(192.168.122.127)${RESET}"
echo -e "│   ├── MySQL 8.0"
echo -e "│   └── Node Exporter :9100"
echo ""
echo -e "├── ${BLUE}sre-mon${RESET} ${YELLOW}(192.168.122.218)${RESET}"
echo -e "│   ├── Prometheus :9090"
echo -e "│   ├── Grafana :3000"
echo -e "│   └── Node Exporter :9100"
echo ""
echo -e "├── ${BLUE}sre-fail${RESET} ${YELLOW}(192.168.122.224)${RESET}"
echo -e "│   └── Failure Simulation Lab"
echo ""
echo -e "└── ${BLUE}sre-container${RESET} ${YELLOW}(192.168.122.73)${RESET}"
echo -e "    └── Podman Testing Ground"
echo ""
echo -e "${CYAN}═══════════════════════════════════════════════════════${RESET}"
echo -e "${YELLOW}Total VMs: 5 | All managed via systemd + KVM${RESET}"
echo -e "${CYAN}═══════════════════════════════════════════════════════${RESET}"
echo ""
